print("Hello World!")
print("Hello again!")
print("I like to print this")
print("Yes! I'm printing it")
print("It is fun")
print('This work is like magic!')
print('I would say it is cool!')
print('A new text line')
#print('ololo')
print("Have a nice day!")